CREATE TABLE `projects` (
  `uuid` varchar(36) NOT NULL,
  `id` int(11) NOT NULL,
  `request` varchar(15) NOT NULL,
  `title` varchar(255) NOT NULL,
  `requester` varchar(255) NOT NULL,
  `analyst` varchar(150) DEFAULT NULL,
  `department` varchar(100) NOT NULL,
  `company` varchar(45) NOT NULL,
  `hours` int(11) NOT NULL,
  `developer` varchar(100) DEFAULT NULL,
  `begin` date DEFAULT NULL,
  `end` date DEFAULT NULL,
  `quick_win` char(1) DEFAULT NULL,
  `type_project` varchar(16) DEFAULT NULL,
  `status` varchar(6) DEFAULT NULL,
  `opened_project` varchar(20) DEFAULT NULL,
  `effort` int(11) DEFAULT 0,
  `execution` int(11) DEFAULT NULL,
  `finish` date DEFAULT NULL,
  `exec_begin` date DEFAULT NULL,
  `exec_end` date DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`,`company`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;